### ISSUE TITLE
Use libcfbuildpack identity interface

### ISSUE THREAD

**Issue by Zanadar** [cloudfoundry/npm-cnb#10]
https://github.com/cloudfoundry/npm-cnb/blob/0da048e762e18d4c8106860f7d9733ceae86ab27/modules/modules.go#L45

Should use: https://github.com/cloudfoundry/libcfbuildpack/blob/master//logger/identifiable.go#L24:6

**Comment by dfreilich** [comment]
@Zanadar as we move to using Packit, we're probably not going to use the libcfbuildpack interface, so I'll close this for now.
