### ISSUE TITLE
What do you think about doing npm install only?

### ISSUE THREAD

**Issue by pyama86** [cloudfoundry/npm-cnb#11]
Hi team!
Thank you for your commitment to cnb.
by the way, I think, we not always need `npm start`.
For example, I usualy make architecture with  javascript for frontend and  php for backend. 
In this case use the web server is httpd or nginx, that's why I can't need `npm start`

do you have a plan for npm only use `npm install`?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by Zanadar** [comment]
So in this case, npm-cnb would just be used for compiling the frontend app, served by php backend?

**Comment by pyama86** [comment]
You are right.
In this case, only javascript library install to `node_modules` by npm .

**Comment by Zanadar** [comment]
You should be able to specify the buildpacks you want to run as an argument to pack ie something like `pack build --buildpacks=org.cloudfoundry.node-engine,org.cloudfoundry.npm,org.cloudfoundry.php-web,org.cloudfoundry.nginx`

**Comment by Zanadar** [comment]
What'll happen in that case is that npm insstall will occur, and then later cnbs will provide app start commands.

**Comment by pyama86** [comment]
oh!! I understand.
Since php-web-cnb and npm-cnb have the same value `processes-> type = web` written in launch.toml, Thats' why When php-web-cnb is executed after npm-cnb, `npm start` is overwritten and not executed

https://github.com/cloudfoundry/npm-cnb/blob/master/modules/modules.go#L97
https://github.com/cloudfoundry/php-web-cnb/blob/master/phpweb/contributor.go#L173

Thank you for your answer!

**Comment by Zanadar** [comment]
Glad I could help. Closing this issue
