### ISSUE TITLE
Cannot upgrade from 0.0.92 to 0.1.1

### ISSUE THREAD

**Issue by fbiville** [cloudfoundry/npm-cnb#13]
**What version of the buildpack you are using?**
0.1.1

**If you were attempting to accomplish a task, what was it you were attempting to do?**
Dependabot [tried to upgrade](https://github.com/projectriff/builder/pull/232) `npm-cnb` from 0.0.92 to 0.1.1 for our custom riff builder, but the CI failed at dependency resolution. 

**What did you expect to happen?**
I would expect the build to carry on.

**What was the actual behavior?**
As you can from the [job logs](https://github.com/projectriff/builder/pull/232/checks?check_run_id=449980594):
```sh
-> unzip /home/runner/go/pkg/mod/cache/download/github.com/cloudfoundry/npm-cnb/@v/v0.1.1.zip: malformed file path "integration/testdata/vendored/node_modules/figlet/fonts/Patorjk's Cheese.flf": invalid char '\''
##[error]Makefile:17: recipe for target 'builder.toml' failed
```

**Comment by scothis** [comment]
fixed in 0.1.2
