### ISSUE TITLE
Rebuild of simple node app using build service fails due to build step error

### ISSUE THREAD

**Issue by mgibson1121** [cloudfoundry/npm-cnb#9]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?

* 0.0.15

If you were attempting to accomplish a task, what was it you were attempting to do?

* Rebuild a simple node app using build service 

What did you expect to happen?

* Rebuild succeeds

What was the actual behavior?

* Error triggered during NPM build step 

```
[build-step-build] unable to copy "/workspace/node_modules" to "/layers/org.cloudfoundry.npm/node_modules": error while creating '/layers/org.cloudfoundry.npm/node_modules/node_modules/.bin/esparse' as symlink to '../esprima/bin/esparse.js': symlink ../esprima/bin/esparse.js /layers/org.cloudfoundry.npm/node_modules/node_modules/.bin/esparse: file exists
[build-step-build] Error: failed to build: exit status 103
```

Can you provide a sample app?

https://github.com/node-modules

Please confirm where necessary:
* [x ] I have included a log output
* [x ] My log includes an error message
* [x ] I have included steps for reproduction

Comment from @ndon55555 

`It seems like we don't handle the case where an app is vendored without a package-lock.json very well.`

**Comment by ForestEckhardt** [comment]
After discussion with @mgibson1121 we are going to close this issue and it can be reopened if this is seen again.
